#
# Data for each cluster
#
oakley:
  hostname:       oakley.osc.edu
  pbshost:        oak-batch.osc.edu
  cluster_code:   Oakley+nodes
ruby:
  hostname:       ruby.osc.edu
  pbshost:        ruby-batch.ten.osc.edu
  cluster_code:   Ruby
